### ISSUE TITLE
Tool does not work on production file

### ISSUE THREAD

**Issue by prondzyn** [29bits/ms-cards-checker#1]
I've run the tool with:

`docker run --rm cards-checker niesap_input.csv`

on the [niesap_input.csv](https://github.com/29bits/ms-cards-checker/files/9838542/niesap_input.csv)

and I'm getting:

```
> docker run --rm cards-checker niesap_input.csv
ERROR: Provided file niesap_input.csv is not a valid csv file or has an invalid format.
See python3 cards_checker.py --help for expected csv structure
```

**Comment by awojtczak** [comment]
Fixed. The issue lied in lack of binding the test file. Please use 
`dockerRun.sh FILE`
to avoid having to mount the file yourself.

Also, remember to run  `./dockerBuildAndRun.sh` after each pull.

**Comment by prondzyn** [comment]
I've run:
```
> ./dockerBuildAndRun.sh
```
and I'm getting error:
```
unable to prepare context: path ".\r" not found
./dockerRun.sh: line 4: syntax error near unexpected token `elif'
'/dockerRun.sh: line 4: `elif [ "$1" = "" ]
```

**Comment by awojtczak** [comment]
What's your OS & environment? Is it maybe windows with WSL?

I think the error you're facing is classic 'end of line characters by windows' 🙃.
I cannot reproduce, but maybe that's what happened:
1. You opened scripts with windows app
2. Saved
3. Tried running in WSL, but unix doesn't work as windows lines endings were applied in step 2.

Try checking out the repo in linux directly maybe? First, please confirm your OS & runtime env.

**Comment by prondzyn** [comment]
Yes it is Windows + WSL.

This issue appears without opening anything. Just after cloning the repo. Probably some additional git repo setup is needed. I will try to figure out if you do not have place to replicate this error.

**Comment by prondzyn** [comment]
`dos2unix` helped
