### ISSUE TITLE
Add optional input "excludedCardsTakenStatuses" param

### ISSUE THREAD

**Issue by prondzyn** [29bits/ms-cards-checker#3]
The script works great. Now I see that one additional feature would be helpful for me.

I would like to be able to specify list of `excludedCardsTakenStatuses`.

Example:

1) with `./dockerRun.sh ../niesap.csv exclude=tak,wpłacił` all records with `odebrał karty?` == `tak` or `odebrał karty?` == `wpłacił` should be excluded.

2) with  `./dockerRun.sh ../niesap.csv` we are assuming `exclude=tak` so all `odebrał karty?` == `tak` should be excluded.

3) also it should be able to filter records where `odebrał karty?` == `""`. We can assume `exclude=EMPTY` in this case

**Comment by awojtczak** [comment]
Done
